name: 02 - Workflow Events

on: 
    #push :                      #multi on in array
    pull_request:
    # schedule: 
    #     - cron: "*/5 * * * *"  
    workflow_dispatch: #manual trigger from UI

jobs: 
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "I am triggered by a(n) ${{ github.event_name }} event."